document.addEventListener("DOMContentLoaded",()=>{chrome.storage.local.get(["selectedText"],e=>{e.selectedText&&(document.getElementById("prompt").value=e.selectedText,chrome.storage.local.remove("selectedText"),document.getElementById("send").click())}),document.getElementById("grok-tab").classList.add("active"),document.getElementById("grok-tab").addEventListener("click",()=>i("grok")),document.getElementById("vocab-tab").addEventListener("click",()=>i("vocab"))});function i(e){document.getElementById("grok-tab").classList.remove("active"),document.getElementById("vocab-tab").classList.remove("active"),document.getElementById(e+"-tab").classList.add("active"),document.getElementById("grok-section").style.display=e==="grok"?"block":"none",document.getElementById("vocab-section").style.display=e==="vocab"?"block":"none"}document.getElementById("extract-vocab").addEventListener("click",()=>{const e=document.getElementById("extract-vocab"),n=document.getElementById("graph-placeholder");e.classList.add("loading"),n.innerHTML="🔄 Extracting vocabulary...",chrome.tabs.query({active:!0,currentWindow:!0},o=>{chrome.scripting.executeScript({target:{tabId:o[0].id},func:()=>document.body.innerText.substring(0,2e4)},c=>{if(chrome.runtime.lastError||!c||!c[0]){e.classList.remove("loading"),n.innerHTML="❌ Error: Could not access page content.";return}const a=c[0].result||"";console.log("Sending content to background, length:",a.length),chrome.runtime.sendMessage({action:"extractVocab",text:a},r=>{console.log("Background response:",r),e.classList.remove("loading"),n.innerHTML="✅ Vocabulary extracted successfully!",setTimeout(()=>l(),500)})})})});document.getElementById("view-full-vocab").addEventListener("click",()=>{chrome.tabs.create({url:chrome.runtime.getURL("vocab.html")})});document.getElementById("refresh-preview").addEventListener("click",()=>{l()});document.getElementById("vocab-tab").addEventListener("click",()=>{l()});async function l(){try{const e=await new Promise(n=>{chrome.runtime.sendMessage({action:"getVocab"},n)});e&&e.words&&(m(e.words,e.translations,e.relations),g(e.words.slice(0,5)),u(e.words.slice(0,10),e.relations))}catch(e){console.error("Error loading vocab preview:",e)}}function m(e,n,o){const c=e?e.length:0,a=o?o.length:0,r=n?n.length:0;document.getElementById("vocab-count").textContent=c,document.getElementById("relation-count").textContent=a,document.getElementById("translation-count").textContent=r;const t=document.getElementById("vocab-stats");c>0?t.style.display="flex":t.style.display="none"}function g(e){const n=document.getElementById("vocab-items"),o=document.getElementById("vocab-empty");if(!e||e.length===0){n.style.display="none",o.style.display="block";return}n.style.display="block",o.style.display="none",n.innerHTML=e.map(c=>`
    <div class="vocab-item">
      <div>
        <span class="vocab-word">${c.text}</span>
        <span class="vocab-pos">${c.pos}</span>
      </div>
      <span class="vocab-score">${c.freq_rank?c.freq_rank.toFixed(1):"0.0"}</span>
    </div>
  `).join("")}function u(e,n){const o=d3.select("#mini-vocab-graph"),c=document.getElementById("graph-placeholder");if(!e||e.length===0){o.style("display","none"),c.style.display="flex";return}o.style("display","block"),c.style.display="none",o.selectAll("*").remove();const a=e.slice(0,8).map((t,s)=>({id:t.id,text:t.text.length>8?t.text.substring(0,6)+"...":t.text,x:s%4*75+40,y:Math.floor(s/4)*40+30,group:t.pos==="Noun"?1:2})),r=[];if(a.length>1)for(let t=0;t<Math.min(a.length-1,3);t++)r.push({source:a[t],target:a[t+1]});o.selectAll("line").data(r).enter().append("line").attr("x1",t=>t.source.x).attr("y1",t=>t.source.y).attr("x2",t=>t.target.x).attr("y2",t=>t.target.y).attr("stroke","#e2e8f0").attr("stroke-width",2),o.selectAll("circle").data(a).enter().append("circle").attr("cx",t=>t.x).attr("cy",t=>t.y).attr("r",12).attr("fill",t=>t.group===1?"#667eea":"#764ba2").attr("stroke","#fff").attr("stroke-width",2),o.selectAll("text").data(a).enter().append("text").attr("x",t=>t.x).attr("y",t=>t.y+4).attr("text-anchor","middle").attr("font-size","9px").attr("font-weight","500").attr("fill","#fff").text(t=>t.text)}document.getElementById("send").addEventListener("click",()=>{const e=document.getElementById("prompt").value.trim(),n=document.getElementById("response"),o=document.getElementById("send");o.classList.add("loading"),n.innerHTML='<div class="loading-text">Processing your query...</div>',chrome.tabs.query({active:!0,currentWindow:!0},c=>{chrome.scripting.executeScript({target:{tabId:c[0].id},func:()=>document.body.innerText.substring(0,1e4)},a=>{if(chrome.runtime.lastError||!a||!a[0]){o.classList.remove("loading"),n.innerHTML='<div class="loading-text">Error: Could not access page content.</div>';return}const r=a[0].result||"",t=e?`Page content (excerpt): ${r}

User query: ${e}`:`Summarize this page: ${r}`;chrome.runtime.sendMessage({action:"sendToGrok",prompt:t},s=>{if(o.classList.remove("loading"),chrome.runtime.lastError)n.innerHTML='<div class="loading-text">Error: '+chrome.runtime.lastError.message+"</div>";else{const d=s.response||"No response received.";n.textContent=d}})})})});
